"""Primary key mixins."""

from __future__ import annotations

import uuid

from sqlalchemy import BigInteger, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPkMixin:
    """Primary key of a business entity: uuid4 generated by the application.

    Attributes:
        id: uuid.UUID - Primary key.

    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )


class BigIntPkMixin:
    """Primary key of an append-only table: logs, outbox.

    Attributes:
        id: int - Primary key.

    """

    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
    )
