"""Mixins combine into mapped models without conflicts."""

from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar, cast

from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, configure_mappers
from sqlalchemy.schema import CreateTable

from vld.core.database import make_metadata
from vld.core.database.mixins import (
    BigIntPkMixin,
    CreatedAtMixin,
    TimestampMixin,
    UUIDPkMixin,
)

if TYPE_CHECKING:
    from sqlalchemy import MetaData, Table


def test_mixins_survive_mapper_configuration() -> None:
    """Both the mutable and the append-only combination configure cleanly."""
    probe_metadata = make_metadata("mixin_probe")

    class Base(DeclarativeBase):
        metadata: ClassVar[MetaData] = probe_metadata

    class Mutable(UUIDPkMixin, TimestampMixin, Base):
        __tablename__: str = "mutable"

    class AppendOnly(BigIntPkMixin, CreatedAtMixin, Base):
        __tablename__: str = "append_only"

    configure_mappers()
    assert Mutable.__mapper__.columns["updated_at"] is not None
    assert AppendOnly.__mapper__.columns["created_at"] is not None


def test_the_bigint_primary_key_is_an_identity_column() -> None:
    """Identity, not serial: the PostgreSQL recommendation and a squawk rule."""
    probe_metadata = make_metadata("identity_probe")

    class Base(DeclarativeBase):
        metadata: ClassVar[MetaData] = probe_metadata

    class Log(BigIntPkMixin, Base):
        __tablename__: str = "log"

    ddl = str(
        CreateTable(
            cast("Table", Log.__table__),
        ).compile(
            dialect=postgresql.dialect(),
        )
    )

    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in ddl
