"""Asynchronous typed client of the Crossref REST API."""

from __future__ import annotations

from ._client import CrossrefClient
from .errors import (
    CrossrefBadRequestError,
    CrossrefBlockedError,
    CrossrefCursorExpiredError,
    CrossrefError,
    CrossrefQueryError,
    CrossrefRateLimitedError,
    CrossrefSchemaError,
    CrossrefUnavailableError,
    ValidationProblem,
)
from .ids import normalize_doi, normalize_issn
from .journals import (
    Journal,
    JournalCounts,
    JournalIssn,
    JournalsQuery,
)
from .models import PartialDate
from .pagination import (
    CURSOR_LIFETIME,
    MAX_OFFSET_WINDOW,
    MAX_ROWS,
    Facet,
    FacetValue,
    Page,
    check_page,
    check_walk,
    page_from_message,
    parse_facets,
    read_items,
    walk,
)
from .throttle import LocalThrottle, RateLimits, Throttle
from .transport import RetryPolicy
from .works.model import (
    Affiliation,
    AffiliationId,
    Agency,
    Assertion,
    AwardAmount,
    ClinicalTrial,
    ContentDomain,
    Contributor,
    ContributorRole,
    Event,
    FreeToRead,
    Funder,
    FunderId,
    Funding,
    Investigator,
    IssnType,
    JournalIssue,
    License,
    Link,
    Project,
    Reference,
    Relation,
    Resources,
    ResourceUrl,
    Review,
    StandardsBody,
    Update,
    Work,
    WorkAgency,
)
from .works.query import (
    FullTextApplication,
    FunderDoiAssertedBy,
    LicenseVersion,
    Order,
    WorkFacet,
    WorkField,
    WorksFilter,
    WorksQuery,
    WorksSort,
    WorkType,
)

__all__ = (
    "CURSOR_LIFETIME",
    "MAX_OFFSET_WINDOW",
    "MAX_ROWS",
    "Affiliation",
    "AffiliationId",
    "Agency",
    "Assertion",
    "AwardAmount",
    "ClinicalTrial",
    "ContentDomain",
    "Contributor",
    "ContributorRole",
    "CrossrefBadRequestError",
    "CrossrefBlockedError",
    "CrossrefClient",
    "CrossrefCursorExpiredError",
    "CrossrefError",
    "CrossrefQueryError",
    "CrossrefRateLimitedError",
    "CrossrefSchemaError",
    "CrossrefUnavailableError",
    "Event",
    "Facet",
    "FacetValue",
    "FreeToRead",
    "FullTextApplication",
    "Funder",
    "FunderDoiAssertedBy",
    "FunderId",
    "Funding",
    "Investigator",
    "IssnType",
    "Journal",
    "JournalCounts",
    "JournalIssn",
    "JournalIssue",
    "JournalsQuery",
    "License",
    "LicenseVersion",
    "Link",
    "LocalThrottle",
    "Order",
    "Page",
    "PartialDate",
    "Project",
    "RateLimits",
    "Reference",
    "Relation",
    "ResourceUrl",
    "Resources",
    "RetryPolicy",
    "Review",
    "StandardsBody",
    "Throttle",
    "Update",
    "ValidationProblem",
    "Work",
    "WorkAgency",
    "WorkFacet",
    "WorkField",
    "WorkType",
    "WorksFilter",
    "WorksQuery",
    "WorksSort",
    "check_page",
    "check_walk",
    "normalize_doi",
    "normalize_issn",
    "page_from_message",
    "parse_facets",
    "read_items",
    "walk",
)
