"""Application layer of auth: ports and use cases."""

from __future__ import annotations

from .ports import (
    AccessClaims,
    Clock,
    DeviceClaims,
    EmailPermanentlyUndeliverableError,
    EmailSender,
    InvalidAccessTokenError,
    Outbox,
    PasswordHasher,
    RateLimiter,
    RefreshClaims,
    RefreshedPairCache,
    RevocationCheckUnavailableError,
    RevocationStore,
    TokenIssuer,
    TokenRepository,
    UserRepository,
    UsersPage,
)
from .use_cases import (
    InvalidTokenError,
    LoginCommand,
    LoginResult,
    LoginWithPassword,
    RegisterCommand,
    RegisterUser,
    ResendVerification,
    ResendVerificationCommand,
    SendPasswordResetEmail,
    SendVerificationEmail,
    TokenPair,
    UnknownRegisteredUserError,
    UnknownResetTargetError,
    VerifyEmail,
    WeakPasswordError,
    warm_password_verification,
)

__all__ = (
    "AccessClaims",
    "Clock",
    "DeviceClaims",
    "EmailPermanentlyUndeliverableError",
    "EmailSender",
    "InvalidAccessTokenError",
    "InvalidTokenError",
    "LoginCommand",
    "LoginResult",
    "LoginWithPassword",
    "Outbox",
    "PasswordHasher",
    "RateLimiter",
    "RefreshClaims",
    "RefreshedPairCache",
    "RegisterCommand",
    "RegisterUser",
    "ResendVerification",
    "ResendVerificationCommand",
    "RevocationCheckUnavailableError",
    "RevocationStore",
    "SendPasswordResetEmail",
    "SendVerificationEmail",
    "TokenIssuer",
    "TokenPair",
    "TokenRepository",
    "UnknownRegisteredUserError",
    "UnknownResetTargetError",
    "UserRepository",
    "UsersPage",
    "VerifyEmail",
    "WeakPasswordError",
    "warm_password_verification",
)
